version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  discord-bot:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    # Uncomment for development with volume mounting
    # volumes:
    #   - ./src:/app/src
    #   - ./logs:/app/logs

volumes:
  redis_data: 