[build]
builder = "dockerfile"

[deploy]
start_command = "npm start"
health_check_path = "/"
health_check_timeout = 30

[env]
NODE_ENV = "production"
PORT = "3000"

# These will be set in Railway dashboard:
# DISCORD_BOT_TOKEN
# DISCORD_CLIENT_ID  
# DISCORD_GUILD_ID
# REDIS_URL
# LOG_LEVEL 